### ISSUE TITLE
Most efficient way to randomly shuffle a BitVector?

### ISSUE THREAD

**Issue by kozross** [IagoAbal/haskell-bv#3]
I could use a Fisher-Yates with some kind of custom ``swap`` operation, but I was wondering if there was a more efficient method I wasn't seeing based on how it's implemented.

**Comment by IagoAbal** [comment]
Hi, I missed this issue, I need to check my GitHub notification settings. Anyways, here is my answer...

The easy way would be to use `toBits`, shuffle the list, then use `fromBits`. This may not perform very well for large bit-vectors, but should be fine for small ones I guess. Another option is to use `setBit` to implement that `swap` operation. Not sure how this will perform, I don't know if GHC is good at optimizing these bit-level operations on integers. You can use [criterion](https://hackage.haskell.org/package/criterion) to micro-benchmark and compare several of these implementations.

The most efficient way is likely something based on `GHC.Integer.GMP.Internals`. Convert a bit-vector to a `MutableByteArray#` (see [exportIntegerToMutableByteArray](https://hackage.haskell.org/package/integer-gmp-1.0.2.0/docs/GHC-Integer-GMP-Internals.html#v:exportIntegerToMutableByteArray)), somehow do the shuffling in-place, then convert this back to a bit-vector.

We could add a `toByteArray :: BV -> ByteArray#` or `toMutableByteArray :: BV -> MutableByteArray#` function to _bv_.
